server:
  port: 8003
spring:
  application:
    name: other-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
    sentinel:
      transport:
        dashboard: 127.0.0.1:8070
feign:
  sentinel:
    enabled: true